gdl90:
    dest: 192.168.10.255:4000
    interval: 1s
    mode: gdl90
    test_payload: STRATUX-NG TEST
    record:
        enable: false
        path: ./gdl90-record.log
    replay:
        enable: false
        path: ./gdl90-record.log
        speed: 1
        loop: false
sim:
    ownship:
        enable: true
        center_lat_deg: 45.5404
        center_lon_deg: -122.9498
        alt_feet: 3000
        ground_kt: 90
        gps_horizontal_accuracy_m: 50
        radius_nm: 0.5
        period: 2m0s
        icao: F00000
        callsign: STRATUX
    traffic:
        enable: true
        count: 6
        radius_nm: 2
        period: 1m30s
        ground_kt: 120
    scenario:
        enable: false
        path: ./configs/scenarios/edgecases.yaml
        start_time_utc: "2020-01-01T00:00:00Z"
        loop: true
web:
    enable: true
    listen: :8080
