# Development config
#
# This config drives the built-in simulator and sends real framed GDL90 over UDP.
# Use `mode: test` only for plain-text UDP debugging.

gdl90:
  # Typical GDL90 UDP port is commonly 4000 in the ecosystem.
  # Adjust as needed for your EFB/testing.
  dest: "192.168.10.255:4000"

  # Output mode:
  # - gdl90 (default): send framed GDL90 (heartbeat + Stratux heartbeat + sim ownship/traffic if enabled)
  # - test: send plain text UDP payloads (debugging only)
  mode: gdl90

  # Go duration string
  interval: 1s

  test_payload: "STRATUX-NG TEST"

sim:
  ownship:
    enable: true
    # Pick a realistic center point for your testing.
    # Hillsboro, Oregon (KHIO) area.
    center_lat_deg: 45.5404
    center_lon_deg: -122.9498
    alt_feet: 3000
    ground_kt: 90
    radius_nm: 0.5
    period: 120s
    # 24-bit ICAO address as 6 hex chars.
    icao: "F00000"
    callsign: "STRATUX"

  # Simulated traffic targets (GDL90 0x14).
  traffic:
    enable: true
    count: 3
    radius_nm: 2.0
    period: 90s
    ground_kt: 120
