# Development config (placeholder UDP broadcast)
#
# NOTE: This is NOT yet real GDL90 framing.
# It exists to validate Wi‑Fi/AP networking end-to-end.

gdl90:
  # Typical GDL90 UDP port is commonly 4000 in the ecosystem.
  # Adjust as needed for your EFB/testing.
  dest: "192.168.10.255:4000"

  # Output mode:
  # - gdl90 (default): send framed GDL90 heartbeat messages
  # - test: send plain text UDP payloads (debugging only)
  mode: gdl90

  # Go duration string
  interval: 1s

  test_payload: "STRATUX-NG TEST"
