package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"stratux-ng/internal/config"
)

func main() {
	var (
		configPath     string
		iface          string
		uplinkIface    string
		outPath        string
		hostapdOut     string
		leaseStr       string
		restartDnsmasq bool
		restartHostapd bool
		applyInternet  bool
		applyMode      bool
	)

	flag.StringVar(&configPath, "config", "", "Path to config.yaml (defaults to STRATUX_NG_CONFIG or /data/stratux-ng/config.yaml)")
	flag.StringVar(&iface, "iface", "ap0", "AP interface name to bind dnsmasq to")
	flag.StringVar(&uplinkIface, "uplink-iface", "wlan0", "Uplink interface for internet pass-through (NAT)")
	flag.StringVar(&outPath, "out", "", "Write dnsmasq config to this path (default: stdout)")
	flag.StringVar(&hostapdOut, "hostapd-out", "", "Write hostapd config to this path (default: disabled)")
	flag.StringVar(&leaseStr, "lease", "12h", "DHCP lease duration (e.g. 12h)")
	flag.BoolVar(&restartDnsmasq, "restart-dnsmasq", false, "Restart dnsmasq after writing -out")
	flag.BoolVar(&restartHostapd, "restart-hostapd", false, "Restart hostapd after writing -hostapd-out")
	flag.BoolVar(&applyInternet, "apply-internet", false, "Apply uplink + internet pass-through (legacy flag; implied by -apply when config enables it).")
	flag.BoolVar(&applyMode, "apply", false, "Apply wifi.mode (AP/client services, interface IPs, uplink, NAT)")
	flag.Parse()

	leaseStr = strings.TrimSpace(leaseStr)
	if leaseStr == "" {
		exitErr(errors.New("-lease must be non-empty"))
	}
	if _, err := time.ParseDuration(leaseStr); err != nil {
		exitErr(fmt.Errorf("invalid -lease %q: %w", leaseStr, err))
	}

	cfg, resolvedPath, err := config.LoadAuto(configPath)
	if err != nil {
		exitErr(err)
	}
	hostapdOut = strings.TrimSpace(hostapdOut)
	if applyMode && hostapdOut == "" {
		hostapdOut = "/etc/hostapd/hostapd.conf"
	}
	if restartHostapd && hostapdOut == "" {
		exitErr(errors.New("-restart-hostapd requires -hostapd-out"))
	}

	iface = strings.TrimSpace(iface)
	if iface == "" {
		exitErr(errors.New("-iface must be non-empty"))
	}
	uplinkIface = strings.TrimSpace(uplinkIface)
	if uplinkIface == "" {
		exitErr(errors.New("-uplink-iface must be non-empty"))
	}
	outPath = strings.TrimSpace(outPath)

	_, apNet, err := net.ParseCIDR(strings.TrimSpace(cfg.WiFi.SubnetCIDR))
	if err != nil {
		exitErr(fmt.Errorf("wifi.subnet_cidr invalid: %w", err))
	}
	mask := net.IP(apNet.Mask).To4()
	if mask == nil {
		exitErr(errors.New("wifi.subnet_cidr must be IPv4"))
	}
	maskStr := mask.String()

	apIP := net.ParseIP(strings.TrimSpace(cfg.WiFi.APIp)).To4()
	if apIP == nil {
		exitErr(errors.New("wifi.ap_ip must be a valid IPv4 address"))
	}

	startIP := net.ParseIP(strings.TrimSpace(cfg.WiFi.DHCPStart)).To4()
	endIP := net.ParseIP(strings.TrimSpace(cfg.WiFi.DHCPEnd)).To4()
	if startIP == nil || endIP == nil {
		exitErr(errors.New("wifi.dhcp_start and wifi.dhcp_end must be valid IPv4 addresses"))
	}
	runAP := cfg.WiFi.Mode == "ap" || cfg.WiFi.Mode == "ap_client"

	// DHCP options: mirror Stratux behavior.
	// Only advertise gateway/DNS when internet pass-through is enabled.
	dhcpOpts := []string{
		"# Provide the Pi as default gateway and DNS.",
	}
	if cfg.WiFi.InternetPassThroughEnabled && cfg.WiFi.UplinkEnable {
		dhcpOpts = append(dhcpOpts,
			"dhcp-option=option:router,"+apIP.String(),
			"dhcp-option=option:dns-server,"+apIP.String(),
		)
	} else {
		// No default route / DNS for clients.
		dhcpOpts = append(dhcpOpts,
			"dhcp-option=3",
			"dhcp-option=6",
		)
	}

	lines := append([]string{
		"# Generated by stratux-ng-wifi-apply",
		"# Source: " + resolvedPath,
		"#",
		"# Bind to the AP interface only.",
		"interface=" + iface,
		"bind-interfaces",
		"",
		"# DHCP range: start,end,netmask,lease",
		"dhcp-range=" + startIP.String() + "," + endIP.String() + "," + maskStr + "," + leaseStr,
		"",
	}, dhcpOpts...)
	lines = append(lines,
		"domain-needed",
		"bogus-priv",
		"",
	)
	content := strings.Join(lines, "\n")
	if hostapdOut != "" {
		hostapdCfg := renderHostapdConfig(cfg, iface, resolvedPath)
		if err := writeFileAtomic(hostapdOut, []byte(hostapdCfg), 0o600); err != nil {
			exitErr(err)
		}
	}

	if outPath == "" {
		if restartDnsmasq {
			exitErr(errors.New("-restart-dnsmasq requires -out"))
		}
		if applyInternet {
			exitErr(errors.New("-apply-internet requires -out (intended for root-run units)"))
		}
		fmt.Print(content)
		return
	}

	if err := writeFileAtomic(outPath, []byte(content), 0o644); err != nil {
		exitErr(err)
	}

	if restartDnsmasq {
		if !runAP {
			fmt.Fprintln(os.Stderr, "info: skipping dnsmasq restart because wifi.mode=client")
		} else if err := restartService("dnsmasq"); err != nil {
			exitErr(err)
		}
	}
	if restartHostapd {
		if !runAP {
			fmt.Fprintln(os.Stderr, "info: skipping hostapd restart because wifi.mode=client")
		} else if err := restartService("hostapd"); err != nil {
			exitErr(err)
		}
	}

	ranUplink := false
	if applyMode {
		var err error
		ranUplink, err = applyWiFiMode(cfg, iface, uplinkIface, apNet, apIP)
		if err != nil {
			// Best-effort by design: return a clear error so systemd logs it.
			exitErr(err)
		}
	}
	if applyInternet && !ranUplink {
		if err := applyUplinkAndNAT(cfg, iface, uplinkIface); err != nil {
			// Best-effort by design: return a clear error so systemd logs it,
			// but callers can prefix the unit ExecStart with '-' to ignore.
			exitErr(err)
		}
	}
}

var errServiceMissing = errors.New("systemd service missing")

func applyWiFiMode(cfg config.Config, apIface, uplinkIface string, apNet *net.IPNet, apIP net.IP) (bool, error) {
	mode := cfg.WiFi.Mode
	runAP := mode == "ap" || mode == "ap_client"
	if runAP {
		if err := configureAPInterface(apIface, apIP, apNet); err != nil {
			return false, err
		}
		if err := setServiceState("hostapd.service", true, true); err != nil {
			return false, err
		}
		if err := setServiceState("dnsmasq.service", true, true); err != nil {
			return false, err
		}
	} else {
		if err := teardownAPInterface(apIface, apIP, apNet); err != nil {
			return false, err
		}
		if err := setServiceState("hostapd.service", false, true); err != nil && !errors.Is(err, errServiceMissing) {
			return false, err
		}
		if err := setServiceState("dnsmasq.service", false, true); err != nil && !errors.Is(err, errServiceMissing) {
			return false, err
		}
	}

	needNM := mode == "ap_client" || mode == "client"
	if needNM {
		if err := setServiceState("NetworkManager.service", true, false); err != nil {
			return false, err
		}
	} else {
		if err := setServiceState("NetworkManager.service", false, false); err != nil && !errors.Is(err, errServiceMissing) {
			return false, err
		}
	}

	ranUplink := false
	if cfg.WiFi.UplinkEnable || cfg.WiFi.InternetPassThroughEnabled {
		if err := applyUplinkAndNAT(cfg, apIface, uplinkIface); err != nil {
			return false, err
		}
		ranUplink = true
	}

	return ranUplink, nil
}

func applyUplinkAndNAT(cfg config.Config, apIface, uplinkIface string) error {
	// Connect to upstream Wi-Fi if configured.
	if cfg.WiFi.UplinkEnable {
		if _, err := exec.LookPath("nmcli"); err == nil {
			var lastErr error
			for _, n := range cfg.WiFi.ClientNetworks {
				ssid := strings.TrimSpace(n.SSID)
				pw := strings.TrimSpace(n.Password)
				if ssid == "" {
					continue
				}
				args := []string{"dev", "wifi", "connect", ssid, "ifname", uplinkIface}
				if pw != "" {
					args = append(args, "password", pw)
				}
				cmd := exec.Command("nmcli", args...)
				cmd.Stdout = os.Stdout
				cmd.Stderr = os.Stderr
				if err := cmd.Run(); err == nil {
					lastErr = nil
					break
				} else {
					lastErr = err
				}
			}
			if lastErr != nil {
				return fmt.Errorf("nmcli connect failed: %w", lastErr)
			}
		} else {
			return errors.New("nmcli not found (cannot apply uplink connection)")
		}
	}

	// Apply forwarding + NAT if enabled.
	if cfg.WiFi.InternetPassThroughEnabled {
		if err := os.WriteFile("/proc/sys/net/ipv4/ip_forward", []byte("1"), 0o644); err != nil {
			// Fall back to sysctl if /proc write fails (some systems require it).
			_ = runCmd("sysctl", []string{"-w", "net.ipv4.ip_forward=1"})
		}
		if err := ensureIptablesRule([]string{"-t", "nat", "POSTROUTING", "-o", uplinkIface, "-j", "MASQUERADE"}); err != nil {
			return err
		}
		if err := ensureIptablesRule([]string{"FORWARD", "-i", uplinkIface, "-o", apIface, "-m", "state", "--state", "RELATED,ESTABLISHED", "-j", "ACCEPT"}); err != nil {
			return err
		}
		if err := ensureIptablesRule([]string{"FORWARD", "-i", apIface, "-o", uplinkIface, "-j", "ACCEPT"}); err != nil {
			return err
		}
	}

	return nil
}

func renderHostapdConfig(cfg config.Config, iface, source string) string {
	var b strings.Builder
	b.WriteString("# Generated by stratux-ng-wifi-apply\n")
	if source != "" {
		b.WriteString("# Source: " + source + "\n")
	}
	b.WriteString("#\n")
	b.WriteString("interface=" + iface + "\n")
	b.WriteString("driver=nl80211\n")
	b.WriteString("country_code=" + cfg.WiFi.Country + "\n")
	b.WriteString("ssid=" + cfg.WiFi.SSID + "\n")
	b.WriteString("hw_mode=g\n")
	b.WriteString(fmt.Sprintf("channel=%d\n", cfg.WiFi.Channel))
	b.WriteString("ieee80211n=1\n")
	b.WriteString("wmm_enabled=1\n")
	if cfg.WiFi.Passphrase == "" {
		b.WriteString("auth_algs=1\n")
	} else {
		b.WriteString("wpa=2\n")
		b.WriteString("wpa_key_mgmt=WPA-PSK\n")
		b.WriteString("rsn_pairwise=CCMP\n")
		b.WriteString("wpa_passphrase=" + cfg.WiFi.Passphrase + "\n")
	}
	b.WriteString("\n")
	return b.String()
}

func configureAPInterface(iface string, apIP net.IP, apNet *net.IPNet) error {
	if iface == "" {
		return fmt.Errorf("configureAPInterface: empty interface")
	}
	if apIP == nil || apNet == nil {
		return fmt.Errorf("configureAPInterface: missing IP or network")
	}
	if _, err := net.InterfaceByName(iface); err != nil {
		return fmt.Errorf("interface %s not found (ensure stratux-ng-create-ap0.service succeeded): %w", iface, err)
	}
	ones, _ := apNet.Mask.Size()
	cidr := fmt.Sprintf("%s/%d", apIP.String(), ones)
	if err := runCmd("ip", []string{"link", "set", iface, "up"}); err != nil {
		return fmt.Errorf("failed to bring %s up: %w", iface, err)
	}
	if err := runCmd("ip", []string{"addr", "replace", cidr, "dev", iface}); err != nil {
		return fmt.Errorf("failed to assign %s to %s: %w", cidr, iface, err)
	}
	return nil
}

func teardownAPInterface(iface string, apIP net.IP, apNet *net.IPNet) error {
	if iface == "" || apIP == nil || apNet == nil {
		return nil
	}
	if _, err := net.InterfaceByName(iface); err != nil {
		return nil
	}
	ones, _ := apNet.Mask.Size()
	cidr := fmt.Sprintf("%s/%d", apIP.String(), ones)
	_ = runCmd("ip", []string{"addr", "del", cidr, "dev", iface})
	_ = runCmd("ip", []string{"link", "set", iface, "down"})
	return nil
}

func setServiceState(service string, enable bool, maskWhenDisable bool) error {
	service = strings.TrimSpace(service)
	if service == "" {
		return fmt.Errorf("setServiceState: empty service name")
	}
	if enable {
		if err := systemctlCmd(service, []string{"unmask"}); err != nil {
			return err
		}
		if err := systemctlCmd(service, []string{"enable", "--now"}); err != nil {
			return err
		}
		return nil
	}
	if err := systemctlCmd(service, []string{"stop"}); err != nil && !errors.Is(err, errServiceMissing) {
		return err
	}
	if err := systemctlCmd(service, []string{"disable"}); err != nil && !errors.Is(err, errServiceMissing) {
		return err
	}
	if maskWhenDisable {
		if err := systemctlCmd(service, []string{"mask"}); err != nil && !errors.Is(err, errServiceMissing) {
			return err
		}
	}
	return nil
}

func systemctlCmd(service string, args []string) error {
	cmdArgs := append(args, service)
	var stderr bytes.Buffer
	cmd := exec.Command("systemctl", cmdArgs...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = &stderr
	if err := cmd.Run(); err != nil {
		msg := strings.TrimSpace(stderr.String())
		lower := strings.ToLower(msg)
		if strings.Contains(lower, "could not be found") || strings.Contains(lower, "not found") || strings.Contains(lower, "not loaded") {
			return fmt.Errorf("%w: %s", errServiceMissing, service)
		}
		if msg == "" {
			msg = err.Error()
		}
		return fmt.Errorf("systemctl %s failed: %s", strings.Join(cmdArgs, " "), msg)
	}
	return nil
}

func ensureIptablesRule(ruleSpec []string) error {
	// ruleSpec is everything after "iptables" excluding the action.
	// Example: ["-t","nat","POSTROUTING","-o","wlan0","-j","MASQUERADE"]
	if len(ruleSpec) == 0 {
		return errors.New("iptables rule spec empty")
	}

	check := append([]string{}, ruleSpec...)
	// Insert -C or -A right after optional -t table.
	if len(check) >= 2 && check[0] == "-t" {
		check = append(check[:2], append([]string{"-C"}, check[2:]...)...)
	} else {
		check = append([]string{"-C"}, check...)
	}
	if err := runCmd("iptables", check); err == nil {
		return nil
	}

	add := append([]string{}, ruleSpec...)
	if len(add) >= 2 && add[0] == "-t" {
		add = append(add[:2], append([]string{"-A"}, add[2:]...)...)
	} else {
		add = append([]string{"-A"}, add...)
	}
	if err := runCmd("iptables", add); err != nil {
		return fmt.Errorf("iptables add failed (%v): %w", strings.Join(add, " "), err)
	}
	return nil
}

func runCmd(name string, args []string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(dir, ".stratux-ng-wifi-apply-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		_ = os.Remove(tmpName)
	}()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

func restartService(name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("restartService: empty service name")
	}
	return systemctlCmd(name, []string{"restart"})
}

func exitErr(err error) {
	_, _ = fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}
