package main

import (
	"errors"
	"flag"
	"fmt"
	"net"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"time"

	"stratux-ng/internal/config"
)

func main() {
	var (
		configPath     string
		iface          string
		uplinkIface    string
		outPath        string
		leaseStr       string
		restartDnsmasq bool
		applyInternet  bool
	)

	flag.StringVar(&configPath, "config", "", "Path to config.yaml (defaults to STRATUX_NG_CONFIG or /data/stratux-ng/config.yaml)")
	flag.StringVar(&iface, "iface", "ap0", "AP interface name to bind dnsmasq to")
	flag.StringVar(&uplinkIface, "uplink-iface", "wlan0", "Uplink interface for internet pass-through (NAT)")
	flag.StringVar(&outPath, "out", "", "Write dnsmasq config to this path (default: stdout)")
	flag.StringVar(&leaseStr, "lease", "12h", "DHCP lease duration (e.g. 12h)")
	flag.BoolVar(&restartDnsmasq, "restart-dnsmasq", false, "Restart dnsmasq after writing -out")
	flag.BoolVar(&applyInternet, "apply-internet", false, "Apply uplink + internet pass-through (nmcli connect, ip_forward, iptables NAT). Best-effort; intended for root-run units.")
	flag.Parse()

	leaseStr = strings.TrimSpace(leaseStr)
	if leaseStr == "" {
		exitErr(errors.New("-lease must be non-empty"))
	}
	if _, err := time.ParseDuration(leaseStr); err != nil {
		exitErr(fmt.Errorf("invalid -lease %q: %w", leaseStr, err))
	}

	cfg, resolvedPath, err := config.LoadAuto(configPath)
	if err != nil {
		exitErr(err)
	}

	iface = strings.TrimSpace(iface)
	if iface == "" {
		exitErr(errors.New("-iface must be non-empty"))
	}
	uplinkIface = strings.TrimSpace(uplinkIface)
	if uplinkIface == "" {
		exitErr(errors.New("-uplink-iface must be non-empty"))
	}

	_, apNet, err := net.ParseCIDR(strings.TrimSpace(cfg.WiFi.SubnetCIDR))
	if err != nil {
		exitErr(fmt.Errorf("wifi.subnet_cidr invalid: %w", err))
	}
	mask := net.IP(apNet.Mask).To4()
	if mask == nil {
		exitErr(errors.New("wifi.subnet_cidr must be IPv4"))
	}
	maskStr := mask.String()

	apIP := net.ParseIP(strings.TrimSpace(cfg.WiFi.APIp)).To4()
	if apIP == nil {
		exitErr(errors.New("wifi.ap_ip must be a valid IPv4 address"))
	}

	startIP := net.ParseIP(strings.TrimSpace(cfg.WiFi.DHCPStart)).To4()
	endIP := net.ParseIP(strings.TrimSpace(cfg.WiFi.DHCPEnd)).To4()
	if startIP == nil || endIP == nil {
		exitErr(errors.New("wifi.dhcp_start and wifi.dhcp_end must be valid IPv4 addresses"))
	}

	// DHCP options: mirror Stratux behavior.
	// Only advertise gateway/DNS when internet pass-through is enabled.
	dhcpOpts := []string{
		"# Provide the Pi as default gateway and DNS.",
	}
	if cfg.WiFi.InternetPassThroughEnabled && cfg.WiFi.UplinkEnable {
		dhcpOpts = append(dhcpOpts,
			"dhcp-option=option:router,"+apIP.String(),
			"dhcp-option=option:dns-server,"+apIP.String(),
		)
	} else {
		// No default route / DNS for clients.
		dhcpOpts = append(dhcpOpts,
			"dhcp-option=3",
			"dhcp-option=6",
		)
	}

	lines := append([]string{
		"# Generated by stratux-ng-wifi-apply",
		"# Source: " + resolvedPath,
		"#",
		"# Bind to the AP interface only.",
		"interface=" + iface,
		"bind-interfaces",
		"",
		"# DHCP range: start,end,netmask,lease",
		"dhcp-range=" + startIP.String() + "," + endIP.String() + "," + maskStr + "," + leaseStr,
		"",
	}, dhcpOpts...)
	lines = append(lines,
		"domain-needed",
		"bogus-priv",
		"",
	)
	content := strings.Join(lines, "\n")

	if strings.TrimSpace(outPath) == "" {
		if restartDnsmasq {
			exitErr(errors.New("-restart-dnsmasq requires -out"))
		}
		if applyInternet {
			exitErr(errors.New("-apply-internet requires -out (intended for root-run units)"))
		}
		fmt.Print(content)
		return
	}

	if err := writeFileAtomic(outPath, []byte(content), 0o644); err != nil {
		exitErr(err)
	}

	if restartDnsmasq {
		if err := restartService("dnsmasq"); err != nil {
			exitErr(err)
		}
	}

	if applyInternet {
		if err := applyUplinkAndNAT(cfg, iface, uplinkIface); err != nil {
			// Best-effort by design: return a clear error so systemd logs it,
			// but callers can prefix the unit ExecStart with '-' to ignore.
			exitErr(err)
		}
	}
}

func applyUplinkAndNAT(cfg config.Config, apIface, uplinkIface string) error {
	// Connect to upstream Wi-Fi if configured.
	if cfg.WiFi.UplinkEnable {
		if _, err := exec.LookPath("nmcli"); err == nil {
			var lastErr error
			for _, n := range cfg.WiFi.ClientNetworks {
				ssid := strings.TrimSpace(n.SSID)
				pw := strings.TrimSpace(n.Password)
				if ssid == "" {
					continue
				}
				args := []string{"dev", "wifi", "connect", ssid, "ifname", uplinkIface}
				if pw != "" {
					args = append(args, "password", pw)
				}
				cmd := exec.Command("nmcli", args...)
				cmd.Stdout = os.Stdout
				cmd.Stderr = os.Stderr
				if err := cmd.Run(); err == nil {
					lastErr = nil
					break
				} else {
					lastErr = err
				}
			}
			if lastErr != nil {
				return fmt.Errorf("nmcli connect failed: %w", lastErr)
			}
		} else {
			return errors.New("nmcli not found (cannot apply uplink connection)")
		}
	}

	// Apply forwarding + NAT if enabled.
	if cfg.WiFi.InternetPassThroughEnabled {
		if err := os.WriteFile("/proc/sys/net/ipv4/ip_forward", []byte("1"), 0o644); err != nil {
			// Fall back to sysctl if /proc write fails (some systems require it).
			_ = runCmd("sysctl", []string{"-w", "net.ipv4.ip_forward=1"})
		}
		if err := ensureIptablesRule([]string{"-t", "nat", "POSTROUTING", "-o", uplinkIface, "-j", "MASQUERADE"}); err != nil {
			return err
		}
		if err := ensureIptablesRule([]string{"FORWARD", "-i", uplinkIface, "-o", apIface, "-m", "state", "--state", "RELATED,ESTABLISHED", "-j", "ACCEPT"}); err != nil {
			return err
		}
		if err := ensureIptablesRule([]string{"FORWARD", "-i", apIface, "-o", uplinkIface, "-j", "ACCEPT"}); err != nil {
			return err
		}
	}

	return nil
}

func ensureIptablesRule(ruleSpec []string) error {
	// ruleSpec is everything after "iptables" excluding the action.
	// Example: ["-t","nat","POSTROUTING","-o","wlan0","-j","MASQUERADE"]
	if len(ruleSpec) == 0 {
		return errors.New("iptables rule spec empty")
	}

	check := append([]string{}, ruleSpec...)
	// Insert -C or -A right after optional -t table.
	if len(check) >= 2 && check[0] == "-t" {
		check = append(check[:2], append([]string{"-C"}, check[2:]...)...)
	} else {
		check = append([]string{"-C"}, check...)
	}
	if err := runCmd("iptables", check); err == nil {
		return nil
	}

	add := append([]string{}, ruleSpec...)
	if len(add) >= 2 && add[0] == "-t" {
		add = append(add[:2], append([]string{"-A"}, add[2:]...)...)
	} else {
		add = append([]string{"-A"}, add...)
	}
	if err := runCmd("iptables", add); err != nil {
		return fmt.Errorf("iptables add failed (%v): %w", strings.Join(add, " "), err)
	}
	return nil
}

func runCmd(name string, args []string) error {
	cmd := exec.Command(name, args...)
	cmd.Stdout = os.Stdout
	cmd.Stderr = os.Stderr
	return cmd.Run()
}

func writeFileAtomic(path string, data []byte, perm os.FileMode) error {
	dir := filepath.Dir(path)
	if err := os.MkdirAll(dir, 0o755); err != nil {
		return err
	}

	tmp, err := os.CreateTemp(dir, ".stratux-ng-wifi-apply-*.tmp")
	if err != nil {
		return err
	}
	tmpName := tmp.Name()
	defer func() {
		_ = os.Remove(tmpName)
	}()

	if _, err := tmp.Write(data); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Chmod(perm); err != nil {
		_ = tmp.Close()
		return err
	}
	if err := tmp.Close(); err != nil {
		return err
	}
	return os.Rename(tmpName, path)
}

func restartService(name string) error {
	name = strings.TrimSpace(name)
	if name == "" {
		return fmt.Errorf("restartService: empty service name")
	}
	// Use exec.Command so PATH lookup works when systemctl isn't at /bin/systemctl.
	return runCmd("systemctl", []string{"restart", name})
}

func exitErr(err error) {
	_, _ = fmt.Fprintln(os.Stderr, "error:", err)
	os.Exit(1)
}
